name: Deploy Spring Boot to Cloud Run

on:
  push:
    branches:
      # - main
      - deploy/inmemory

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: celestial-air-455806-v8
      REPOSITORY_NAME: library-repo-01
      SERVICE_NAME: library-app
      REGION: asia-northeast1
      REGISTRY_DOMAIN: asia-northeast1-docker.pkg.dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGISTRY_DOMAIN }}

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ env.REGISTRY_DOMAIN }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA .
          docker push ${{ env.REGISTRY_DOMAIN }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.REGISTRY_DOMAIN }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA \
            --platform=managed \
            --region=${{ env.REGION }} \
            --allow-unauthenticated
